# Generated by Django 2.0.2 on 2019-05-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField(max_length=220)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
